USE master;
GO
--CRIAR banco de dados
CREATE DATABASE MovimentosManuais;
GO
USE MovimentosManuais;
GO
--Criar tabela PRODUTO 
Create Table PRODUTO (
	COD_PRODUTO  int primary key IDENTITY(1,1),
	DES_PRODUTO varchar(30),
	STA_STATUS char(1)
);
GO

--Criar tabela PRODUTO_COSIF
Create Table PRODUTO_COSIF(
	COD_COSIF int IDENTITY(1,1),
	COD_PRODUTO int,
	COD_CLASSIFICACAO char(6),
	STA_STATUS char(1),
	constraint FK_PRODUTO foreign key (COD_PRODUTO) references PRODUTO(COD_PRODUTO),
	constraint PK_PRODUTO_COSIF primary key(COD_COSIF, COD_PRODUTO)
);
GO

--Criar tabela MOVIMENTO_MANUAL 
Create Table MOVIMENTO_MANUAL ( 
	DAT_MES int,
	DAT_ANO int,
	NUM_LANCAMENTO int,
	COD_PRODUTO int,
	COD_COSIF int,
	VAL_VALOR int,
	DES_DESCRICAO varchar(50),
	DAT_MOVIMENTO smalldatetime,
	COD_USUARIO varchar(15),
	constraint FK_PRODUTO_COSIF foreign key(COD_COSIF, COD_PRODUTO) references PRODUTO_COSIF(COD_COSIF, COD_PRODUTO),
	constraint PK_MOVIMENTO_MANUAL primary key(DAT_MES, DAT_ANO, NUM_LANCAMENTO, COD_PRODUTO, COD_COSIF)
);
GO
--Criar Procedure
CREATE PROCEDURE ListarMovimentoProduto
AS
SELECT 
mm.DAT_MES, 
mm.DAT_ANO,
mm.COD_PRODUTO,
p.DES_PRODUTO,
mm.NUM_LANCAMENTO,
mm.DES_DESCRICAO,
mm.VAL_VALOR
FROM MOVIMENTO_MANUAL mm
INNER JOIN PRODUTO p ON mm.COD_PRODUTO = p.COD_PRODUTO
ORDER BY mm.DAT_MES, mm.DAT_ANO, mm.NUM_LANCAMENTO;
GO

INSERT INTO [dbo].[PRODUTO] ([DES_PRODUTO] ,[STA_STATUS]) VALUES ('PRODUTO 1' , 'A');
INSERT INTO [dbo].[PRODUTO] ([DES_PRODUTO] ,[STA_STATUS]) VALUES ('PRODUTO 2' , 'I');
INSERT INTO [dbo].[PRODUTO] ([DES_PRODUTO] ,[STA_STATUS]) VALUES ('PRODUTO 3' , 'A');
INSERT INTO [dbo].[PRODUTO] ([DES_PRODUTO] ,[STA_STATUS]) VALUES ('PRODUTO 4' , 'A');

INSERT INTO [dbo].[PRODUTO_COSIF] ([COD_PRODUTO] ,[COD_CLASSIFICACAO] ,[STA_STATUS]) VALUES (1 , 'NORMAL' , 'A');
INSERT INTO [dbo].[PRODUTO_COSIF] ([COD_PRODUTO] ,[COD_CLASSIFICACAO] ,[STA_STATUS]) VALUES (1 , 'MTM' , 'I');
INSERT INTO [dbo].[PRODUTO_COSIF] ([COD_PRODUTO] ,[COD_CLASSIFICACAO] ,[STA_STATUS]) VALUES (2 , 'NORMAL' , 'A');
INSERT INTO [dbo].[PRODUTO_COSIF] ([COD_PRODUTO] ,[COD_CLASSIFICACAO] ,[STA_STATUS]) VALUES (2 , 'MTM' , 'A');
INSERT INTO [dbo].[PRODUTO_COSIF] ([COD_PRODUTO] ,[COD_CLASSIFICACAO] ,[STA_STATUS]) VALUES (3 , 'NORMAL' , 'A');
INSERT INTO [dbo].[PRODUTO_COSIF] ([COD_PRODUTO] ,[COD_CLASSIFICACAO] ,[STA_STATUS]) VALUES (3 , 'MTM' , 'A');
INSERT INTO [dbo].[PRODUTO_COSIF] ([COD_PRODUTO] ,[COD_CLASSIFICACAO] ,[STA_STATUS]) VALUES (4 , 'NORMAL' , 'A');
INSERT INTO [dbo].[PRODUTO_COSIF] ([COD_PRODUTO] ,[COD_CLASSIFICACAO] ,[STA_STATUS]) VALUES (4 , 'MTM' , 'A');